create table places
(
    id bigint primary key generated by default as identity,
    name text not null,
    constraint chk_places_name_len check(length(name) <= 255),
    address text not null,
    constraint chk_places_address_len check(length(address) <= 255),
    link text,
    slug text not null unique,
    constraint chk_places_slug_len check(length(slug) <= 255),
    inverted_logo bool default false
);

create table gigs
(
    id bigint primary key generated by default as identity,
    datetime timestamptz not null,
    place_id bigint references places(id),
    description text,
    constraint chk_gigs_desc_len check(length(description) <= 255),
    url text,
    constraint chk_gigs_url_len check(length(url) <= 255)
);
create index idx_gigs_place_id on gigs(place_id);

create table instruments
(
    id bigint primary key generated by default as identity,
    ru_name text not null unique,
    constraint chk_instruments_ru_name_len check(length(ru_name) <= 100),
    en_name text not null unique,
    constraint chk_instruments_en_name_len check(length(en_name) <= 100)
);

create table members
(
    id bigint primary key generated by default as identity,
    ru_name text not null,
    constraint chk_members_ru_name_len check(length(ru_name) <= 100),
    full_name text,
    constraint chk_members_full_name_len check(length(full_name) <= 255),
    en_name text not null,
    constraint chk_members_en_name_len check(length(en_name) <= 100),
    weight int not null default 0,
    actual bool not null default true,
    instrument_id bigint references instruments(id)
);
create index idx_members_instrument_id on members(instrument_id);

create table albums
(
    id bigint primary key generated by default as identity,
    name text not null,
    constraint chk_albums_name_len check(length(name) <= 255),
    year int not null,
    type text not null,
    constraint chk_albums_type_val check(type in ('album', 'single')),
    ignore bool default false,
    slug text not null unique,
    constraint chk_albums_slug_len check(length(slug) <= 255),
    date date
);

create table album_links
(
    id bigint primary key generated by default as identity,
    album_id bigint references albums(id) on delete cascade,
    url text not null,
    constraint chk_album_links_url_len check(length(url) <= 255)
);
create index idx_album_links_album_id on album_links(album_id);

create table songs
(
    id bigint primary key generated by default as identity,
    name text not null,
    constraint chk_songs_name_len check(length(name) <= 255),
    slug text not null unique,
    constraint chk_songs_slug_len check(length(slug) <= 255)
);

create table lyrics
(
    id bigint primary key generated by default as identity,
    song_id bigint references songs(id),
    text text not null
);
create index idx_lyrics_song_id on lyrics(song_id);

create table songs_on_albums
(
    album_id bigint references albums(id),
    song_id bigint references songs(id),
    position int not null,
    primary key (album_id, song_id)
);
create index idx_songs_on_albums_album_id on songs_on_albums(album_id);
create index idx_songs_on_albums_song_id on songs_on_albums(song_id);
